"""
WIA Security Ecosystem Integration
Phase 4: Threat Intel Feeds, SOAR, Cloud Security
"""

from .threat_intel import (
    ThreatIntelFeedConfig,
    IoC,
    ThreatFeed,
    MispConfig,
    MispClient,
    OtxConfig,
    OtxClient,
    VirusTotalConfig,
    VirusTotalClient,
    create_misp_client,
    create_otx_client,
    create_virustotal_client,
)

from .soar import (
    SoarConfig,
    PlaybookAction,
    Playbook,
    SoarCase,
    Artifact,
    PhantomConfig,
    PhantomClient,
    XsoarConfig,
    XsoarClient,
    ShuffleConfig,
    ShuffleClient,
    create_phantom_client,
    create_xsoar_client,
    create_shuffle_client,
)

from .cloud import (
    CloudSecurityConfig,
    CloudFinding,
    AwsSecurityHubConfig,
    AwsSecurityHubClient,
    AzureSentinelConfig,
    AzureSentinelClient,
    GcpSccConfig,
    GcpSccClient,
    create_aws_security_hub_client,
    create_azure_sentinel_client,
    create_gcp_scc_client,
)

from .dashboard import (
    DashboardMetrics,
    SeverityDistribution,
    TimeSeriesPoint,
    TacticCount,
    TechniqueCount,
    AlertStats,
    ThreatLandscape,
    ComplianceStatus,
    ControlStatus,
    DashboardAggregator,
    ComplianceTracker,
    create_dashboard_aggregator,
    create_compliance_tracker,
)

__all__ = [
    # Threat Intel
    "ThreatIntelFeedConfig",
    "IoC",
    "ThreatFeed",
    "MispConfig",
    "MispClient",
    "OtxConfig",
    "OtxClient",
    "VirusTotalConfig",
    "VirusTotalClient",
    "create_misp_client",
    "create_otx_client",
    "create_virustotal_client",
    # SOAR
    "SoarConfig",
    "PlaybookAction",
    "Playbook",
    "SoarCase",
    "Artifact",
    "PhantomConfig",
    "PhantomClient",
    "XsoarConfig",
    "XsoarClient",
    "ShuffleConfig",
    "ShuffleClient",
    "create_phantom_client",
    "create_xsoar_client",
    "create_shuffle_client",
    # Cloud
    "CloudSecurityConfig",
    "CloudFinding",
    "AwsSecurityHubConfig",
    "AwsSecurityHubClient",
    "AzureSentinelConfig",
    "AzureSentinelClient",
    "GcpSccConfig",
    "GcpSccClient",
    "create_aws_security_hub_client",
    "create_azure_sentinel_client",
    "create_gcp_scc_client",
    # Dashboard
    "DashboardMetrics",
    "SeverityDistribution",
    "TimeSeriesPoint",
    "TacticCount",
    "TechniqueCount",
    "AlertStats",
    "ThreatLandscape",
    "ComplianceStatus",
    "ControlStatus",
    "DashboardAggregator",
    "ComplianceTracker",
    "create_dashboard_aggregator",
    "create_compliance_tracker",
]
