//! Protocol demonstration example
//!
//! This example demonstrates the WIA Physics Protocol (WPP) features
//! using a mock transport for testing.

use wia_physics::prelude::*;
use wia_physics::protocol::*;
use wia_physics::transport::*;

#[tokio::main]
async fn main() -> PhysicsResult<()> {
    println!("=== WIA Physics Protocol Demo ===\n");

    // =========================================================================
    // 1. Create Mock Transport and Connect
    // =========================================================================
    println!("1. Creating mock transport and connecting...");
    println!("{}", "-".repeat(50));

    let mut transport = MockTransport::new();
    transport.connect().await?;
    println!("   Connected: {}", transport.is_connected());

    // =========================================================================
    // 2. Send Connect Message
    // =========================================================================
    println!("\n2. Sending connect message...");
    println!("{}", "-".repeat(50));

    let connect_msg = WppMessage::connect("demo-client", "Physics Demo App");
    println!("   Message ID: {}", connect_msg.id);
    println!("   Type: {:?}", connect_msg.msg_type);

    transport.send(connect_msg).await?;

    // Receive connect_ack (auto-generated by mock)
    let response = transport.receive().await?;
    println!("   Response type: {:?}", response.msg_type);

    if let MessagePayload::ConnectAck(ack) = response.payload {
        println!("   Session ID: {}", ack.session_id);
        println!("   Server: {:?}", ack.server_name);
        println!("   Available channels: {}", ack.channels.len());
        for ch in &ack.channels {
            println!("     - {} ({:?})", ch.name, ch.channel_type);
        }
    }

    // =========================================================================
    // 3. Subscribe to Channel
    // =========================================================================
    println!("\n3. Subscribing to fusion/iter/plasma...");
    println!("{}", "-".repeat(50));

    let subscribe_msg = WppMessage::subscribe("fusion/iter/plasma");
    transport.send(subscribe_msg).await?;

    let response = transport.receive().await?;
    if let MessagePayload::SubscribeAck(ack) = response.payload {
        println!("   Channel: {}", ack.channel);
        println!("   Subscription ID: {}", ack.subscription_id);
        println!("   Status: {:?}", ack.status);
    }

    // =========================================================================
    // 4. Send Data Message
    // =========================================================================
    println!("\n4. Creating and sending data message...");
    println!("{}", "-".repeat(50));

    let fusion_data = FusionDataBuilder::new()
        .experiment("ITER")
        .plasma_simple(150e6, "K", 1e20, "m^-3")
        .tokamak(5.3, 6.2, 2.0)
        .quality(QualityFlag::Simulated)
        .build()?;

    let data_msg = WppMessage::data(
        "fusion/iter/plasma",
        DataType::Fusion,
        &fusion_data,
        1,
    )?;

    println!("   Data message created");
    println!("   Channel: fusion/iter/plasma");
    println!("   Sequence: 1");

    let json = data_msg.to_json()?;
    println!("   JSON size: {} bytes", json.len());

    // =========================================================================
    // 5. Send Command
    // =========================================================================
    println!("\n5. Sending command...");
    println!("{}", "-".repeat(50));

    let cmd_msg = WppMessage::command(
        "fusion/iter/heating/icrf",
        "set_power",
        serde_json::json!({
            "power": 10.0,
            "unit": "MW",
            "ramp_time": 5.0
        }),
    );

    transport.send(cmd_msg.clone()).await?;
    println!("   Command: set_power");
    println!("   Target: fusion/iter/heating/icrf");

    let response = transport.receive().await?;
    if let MessagePayload::Response(resp) = response.payload {
        println!("   Command ID: {}", resp.command_id);
        println!("   Status: {:?}", resp.status);
        println!("   Execution time: {:?} ms", resp.execution_time);
    }

    // =========================================================================
    // 6. Ping/Pong
    // =========================================================================
    println!("\n6. Testing ping/pong...");
    println!("{}", "-".repeat(50));

    let ping = WppMessage::ping();
    let ping_time = std::time::Instant::now();
    transport.send(ping.clone()).await?;

    let pong = transport.receive().await?;
    let latency = ping_time.elapsed();

    if let MessagePayload::Pong(p) = pong.payload {
        println!("   Ping ID: {}", ping.id);
        println!("   Pong received for: {}", p.ping_id);
        println!("   Round-trip latency: {:?}", latency);
    }

    // =========================================================================
    // 7. Channel Matching
    // =========================================================================
    println!("\n7. Testing channel pattern matching...");
    println!("{}", "-".repeat(50));

    let channels = vec![
        "fusion/iter/plasma".to_string(),
        "fusion/jet/plasma".to_string(),
        "fusion/iter/magnets".to_string(),
        "particle/lhc/atlas".to_string(),
    ];

    let patterns = vec![
        "fusion/*/plasma",
        "fusion/iter/*",
        "fusion/**",
        "particle/**",
    ];

    for pattern in patterns {
        let matches = ChannelMatcher::find_matching(&channels, pattern);
        println!("   Pattern '{}' matches:", pattern);
        for m in matches {
            println!("     - {}", m);
        }
    }

    // =========================================================================
    // 8. Error Message
    // =========================================================================
    println!("\n8. Creating error message...");
    println!("{}", "-".repeat(50));

    let error_msg = WppMessage::error(
        error_codes::CHANNEL_NOT_FOUND,
        ErrorCategory::Subscription,
        "Channel 'fusion/unknown/plasma' not found",
    );

    if let MessagePayload::Error(err) = error_msg.payload {
        println!("   Error code: {}", err.code);
        println!("   Category: {:?}", err.category);
        println!("   Message: {}", err.message);
    }

    // =========================================================================
    // 9. Disconnect
    // =========================================================================
    println!("\n9. Disconnecting...");
    println!("{}", "-".repeat(50));

    let disconnect_msg = WppMessage::disconnect(
        DisconnectReason::ClientShutdown,
        Some("Demo complete"),
    );
    transport.send(disconnect_msg).await?;
    transport.disconnect().await?;

    println!("   Disconnected");

    // =========================================================================
    // 10. Transport Stats
    // =========================================================================
    println!("\n10. Transport statistics:");
    println!("{}", "-".repeat(50));

    let stats = transport.stats().await;
    println!("   Messages sent: {}", stats.messages_sent);
    println!("   Messages received: {}", stats.messages_received);
    println!("   Bytes sent: {}", stats.bytes_sent);
    println!("   Bytes received: {}", stats.bytes_received);

    // =========================================================================
    // Summary
    // =========================================================================
    println!("\n{}", "=".repeat(50));
    println!("Demo Complete!");
    println!("{}", "=".repeat(50));

    println!("\nWIA Physics Protocol (WPP) Features Demonstrated:");
    println!("  - Connection management (connect, disconnect)");
    println!("  - Channel subscription");
    println!("  - Physics data streaming");
    println!("  - Command/response");
    println!("  - Ping/pong keepalive");
    println!("  - Channel pattern matching");
    println!("  - Error handling");
    println!("  - Transport statistics");

    println!("\n弘益人間 - Benefit All Humanity 🤟\n");

    Ok(())
}
