/**
 * WIA-SOC-004 Digital Citizenship Standard - TypeScript Type Definitions
 * @module @wia/digital-citizenship/types
 */

// ============================================================================
// Core Identity Types
// ============================================================================

export interface PersonalInfo {
  firstName: string;
  lastName: string;
  dateOfBirth: string; // ISO 8601 format: YYYY-MM-DD
  nationality: string; // ISO 3166-1 alpha-2 country code
  placeOfBirth?: string;
  gender?: 'male' | 'female' | 'other' | 'prefer_not_to_say';
  email?: string;
  phoneNumber?: string;
}

export interface BiometricTemplate {
  template: string; // Base64 encoded biometric template
  algorithm: string; // e.g., "ISO/IEC 19794-2" for fingerprint
  quality: number; // Quality score 0-100
  capturedAt: string; // ISO 8601 timestamp
}

export interface Biometrics {
  fingerprint?: BiometricTemplate;
  faceId?: BiometricTemplate;
  iris?: BiometricTemplate;
  voicePrint?: BiometricTemplate;
  behavioral?: {
    keystrokeDynamics?: string;
    gestureDynamics?: string;
  };
}

export interface Credential {
  type: 'GovernmentID' | 'Passport' | 'DriverLicense' | 'EducationDegree' | 'ProfessionalLicense' | 'BankAccount' | 'Other';
  issuer: string; // Issuing authority
  documentNumber: string;
  issuedDate: string; // ISO 8601 format
  expiryDate?: string; // ISO 8601 format
  verificationStatus: 'pending' | 'verified' | 'rejected' | 'expired';
  verificationDate?: string;
  verificationMethod?: 'automated' | 'manual' | 'in_person' | 'video';
  metadata?: Record<string, any>;
}

export interface DigitalIdentity {
  citizenId: string; // WIA-XXXXXXXXX format
  version: string; // Standard version, e.g., "1.0"
  personalInfo: PersonalInfo;
  biometrics?: Biometrics;
  credentials: Credential[];
  assuranceLevel: 1 | 2 | 3 | 4; // Identity assurance level (IAL)
  trustScore: number; // 0-100
  status: 'active' | 'suspended' | 'revoked';
  createdAt: string; // ISO 8601 timestamp
  updatedAt: string; // ISO 8601 timestamp
  metadata?: Record<string, any>;
}

// ============================================================================
// Rights Management Types
// ============================================================================

export interface PrivacyRights {
  dataAccess: boolean; // Right to access personal data
  dataRectification: boolean; // Right to correct data
  dataErasure: boolean; // Right to be forgotten
  dataPortability: boolean; // Right to export data
  processingRestriction: boolean; // Right to restrict processing
  objectToProcessing: boolean; // Right to object to automated decisions
}

export interface ExpressionRights {
  protectedSpeech: boolean; // Freedom of expression
  anonymousCommunication: boolean; // Right to anonymous communication
  endToEndEncryption: boolean; // Right to encrypted communication
}

export interface EconomicRights {
  digitalPropertyOwnership: boolean; // Right to own digital property
  financialServicesAccess: boolean; // Right to access financial services
  fairDataCompensation: boolean; // Right to fair compensation for data
}

export interface ProtectionRights {
  antiDiscrimination: boolean; // Protection against discrimination
  harassmentProtection: boolean; // Protection from harassment
  minorProtection: boolean; // Special protections for minors
  surveillanceProtection: boolean; // Protection from unauthorized surveillance
  algorithmicBiasProtection: boolean; // Protection from algorithmic bias
}

export interface DigitalRights {
  citizenId: string;
  privacy: PrivacyRights;
  expression: ExpressionRights;
  economic: EconomicRights;
  protection: ProtectionRights;
  jurisdiction: string[]; // ISO 3166-1 alpha-2 country codes
  effectiveDate: string; // ISO 8601 timestamp
  metadata?: Record<string, any>;
}

export interface RightsExerciseRequest {
  requestId?: string; // Generated by server
  citizenId: string;
  rightType: keyof PrivacyRights;
  targetOrganizations: string[]; // Organization IDs
  reason?: string;
  requestedAt?: string; // ISO 8601 timestamp
  status?: 'pending' | 'processing' | 'completed' | 'rejected';
  responseDeadline?: string; // 30 days from request
}

export interface RightsExerciseResponse {
  requestId: string;
  status: 'pending' | 'processing' | 'completed' | 'rejected';
  completedAt?: string;
  organizationResponses: {
    organizationId: string;
    status: 'pending' | 'completed' | 'rejected';
    responseDate?: string;
    dataPackage?: string; // URL or base64 for data portability
    message?: string;
  }[];
}

// ============================================================================
// Verification Types
// ============================================================================

export interface VerificationChallenge {
  type: 'biometric' | 'knowledge' | 'possession' | 'multimodal';
  biometricType?: 'faceId' | 'fingerprint' | 'iris' | 'voice';
  livenessRequired?: boolean;
  qualityThreshold?: number; // 0-100
  knowledgeQuestion?: string;
  possessionToken?: string;
}

export interface VerificationRequest {
  requestId?: string; // Generated by server
  citizenId: string;
  verificationType: 'biometric' | 'knowledge' | 'possession' | 'multimodal';
  challengeData: VerificationChallenge;
  biometricData?: string; // Base64 encoded biometric sample
  knowledgeAnswer?: string;
  possessionProof?: string;
  timestamp?: string; // ISO 8601 timestamp
  nonce?: string; // Random nonce for replay protection
}

export interface VerificationResponse {
  requestId: string;
  verified: boolean;
  confidence: number; // 0-1
  livenessScore?: number; // 0-1
  qualityScore?: number; // 0-1
  assuranceLevel: 1 | 2 | 3 | 4;
  responseTime: number; // Seconds
  timestamp: string; // ISO 8601 timestamp
  signature: string; // Cryptographic signature
  errorCode?: string;
  errorMessage?: string;
}

// ============================================================================
// Cross-Border Types
// ============================================================================

export interface CrossBorderVerification {
  requestId?: string;
  citizenId: string;
  sourceCountry: string; // ISO 3166-1 alpha-2
  targetCountry: string; // ISO 3166-1 alpha-2
  serviceType: 'government' | 'banking' | 'healthcare' | 'education' | 'telecommunications' | 'other';
  requiredAssuranceLevel?: 1 | 2 | 3 | 4;
  timestamp?: string;
}

export interface CrossBorderResponse {
  requestId: string;
  verified: boolean;
  recognized: boolean; // Whether target country recognizes the identity
  assuranceLevel: 1 | 2 | 3 | 4;
  trustScore: number; // 0-100
  responseTime: number; // Seconds
  mutualRecognitionAgreement: boolean;
  timestamp: string;
  signature: string;
}

// ============================================================================
// Client Configuration Types
// ============================================================================

export interface ClientConfig {
  apiKey: string;
  environment: 'production' | 'staging' | 'development';
  region?: 'us-east-1' | 'eu-west-1' | 'ap-southeast-1' | 'global';
  baseUrl?: string; // Custom API endpoint
  timeout?: number; // Request timeout in milliseconds
  retryAttempts?: number;
  enableLogging?: boolean;
}

// ============================================================================
// API Response Types
// ============================================================================

export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  metadata?: {
    requestId: string;
    timestamp: string;
    processingTime: number;
  };
}

export interface PaginatedResponse<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

// ============================================================================
// Event Types
// ============================================================================

export interface IdentityEvent {
  type: 'created' | 'updated' | 'verified' | 'suspended' | 'revoked' | 'deleted';
  citizenId: string;
  timestamp: string;
  metadata?: Record<string, any>;
}

export interface RightsEvent {
  type: 'exercised' | 'granted' | 'revoked' | 'violated';
  citizenId: string;
  rightType: string;
  timestamp: string;
  metadata?: Record<string, any>;
}

export interface VerificationEvent {
  type: 'attempted' | 'succeeded' | 'failed';
  citizenId: string;
  verificationType: string;
  timestamp: string;
  metadata?: Record<string, any>;
}

// ============================================================================
// Statistics Types
// ============================================================================

export interface GlobalStatistics {
  totalCitizens: number;
  activeCitizens: number;
  countriesSupported: number;
  dailyVerifications: number;
  averageResponseTime: number; // Seconds
  systemUptime: number; // Percentage
  trustNetworkSize: number;
}

export interface CitizenStatistics {
  citizenId: string;
  totalVerifications: number;
  successfulVerifications: number;
  failedVerifications: number;
  rightsExercised: number;
  crossBorderAccess: number;
  lastActivity: string; // ISO 8601 timestamp
  accountAge: number; // Days
}
